**<h1>Electric Line Extension - Analysis 1**
#### Descriptive Data
<i>Any question regarding the notebook, please contact Robert Ford or Ria Majumder<br>
    Last Updated: 08/13/2025 | Start Development: 08/13/2025</i>
* Utility / IOU Data from PG&E, SDG&E, and SCE for 2023, 2024, and Q1 2025
* Goals: 1. Clean excel files for public downloads.

In [1]:
#Import Libraries and Packages
import pandas as pd
import numpy as np
import matplotlib as plt

In [16]:
pge_2023_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/PG&E Data_2023.xlsx", header=None)
sdge_2023_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/SDGE Data_2023.xlsx")
sce_2023_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/Attachment A - 2024 Final SCE BE Annual Report.xlsx")

**CLEAN 1**

* For PG&E / SDG&E: Create Residential, Nonresidential, and Mixed-Fuel dataframes
* For SCE: 
* TBD

In [17]:
pge_2023_df.head(20)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Month,Mixed Fuel Projects Requested,Mixed Fuel Projects Energized,All-Electric Projects Requested,All-Electric Projects Energized,All-Electric Upgrades exisitng- Project Requested,All-Electric Upgrades exisitng- Project Energized,Mixed Fuel Upgrades exisitng- Project Requested,Mixed Fuel Upgrades exisitng- Project Energized,Total Upgrades Requested,Total upgrades completed,Total Projects Requested,Total Projects Projects Energized,Percentage All-Electric Requested,Percentage All-electric energized,Percentage of All-Electric Upgrades Requested,Percentage of All-Electric Upgrades completed
2,Jan,291,55,687,86,568,119,4,15,572,134,978,141,70.245399,60.992908,99.300699,88.80597
3,Feb,317,88,736,146,576,205,9,13,585,218,1053,234,69.895537,62.393162,98.461538,94.036697
4,Mar,377,56,988,74,903,124,8,12,911,136,1365,130,72.380952,56.923077,99.121844,91.176471
5,Apr,375,149,1191,206,756,374,11,33,767,407,1566,355,76.05364,58.028169,98.565841,91.891892
6,May,250,134,666,184,603,433,14,37,617,470,916,318,72.707424,57.861635,97.730956,92.12766
7,Jun,276,99,695,155,326,349,6,21,332,370,971,254,71.575695,61.023622,98.192771,94.324324
8,Jul,236,102,599,157,65,257,1,15,66,272,835,259,71.736527,60.617761,98.484848,94.485294
9,Aug,225,126,604,198,48,361,NaN,35,48,396,829,324,72.858866,61.111111,100,91.161616
10,Sep,199,107,560,168,44,343,1,17,45,360,759,275,73.781291,61.090909,97.777778,95.277778
11,Oct,218,109,554,215,55,419,1,29,56,448,772,324,71.761658,66.358025,98.214286,93.526786
12,Nov,196,80,490,174,43,293,1,21,44,314,686,254,71.428571,68.503937,97.727273,93.312102
13,Dec,156,84,426,154,25,300,1,17,26,317,582,238,73.195876,64.705882,96.153846,94.637224
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Total,3116,1189,8196,1917,4012,3577,57,265,4069,3842,11312,3106,72.454031,61.719253,98.599164,93.102551
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Commercial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Month,Mixed Fuel Projects Requested,Mixed Fuel Projects Energized,All-Electric Projects Requested,All-Electric Projects Energized,All-Electric Upgrades exisitng- Project Requested,All-Electric Upgrades exisitng- Project Energized,Mixed Fuel Upgrades exisitng- Project Requested,Mixed Fuel Upgrades exisitng- Project Energized,Total Upgrades Requested,Total upgrades completed,Total Projects Requested,Total Projects Projects Energized,Percentage All-Electric Requested,Percentage All-electric energized,Percentage of All-Electric Upgrades Requested,Percentage of All-Electric Upgrades completed
19,Jan,46,10,190,51,30,17,2,0,32,17,236,61,80.508475,83.606557,93.75,100

In [25]:
pge_2023_df_res = pge_2023_df.iloc[1:16]
pge_2023_df_nonres = pge_2023_df.iloc[18:33]
pge_2023_df_comb = pge_2023_df.iloc[35:50]
pge_2023_df_comb.reset_index()

,index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,35,Month,Mixed Fuel Projects Requested,Mixed Fuel Projects Energized,All-Electric Projects Requested,All-Electric Projects Energized,All-Electric Upgrades exisitng- Project Requested,All-Electric Upgrades exisitng- Project Energized,Mixed Fuel Upgrades exisitng- Project Requested,Mixed Fuel Upgrades exisitng- Project Energized,Total Upgrades Requested,Total upgrades completed,Total Projects Requested,Total Projects Projects Energized,Percentage All-Electric Requested,Percentage All-electric energized,Percentage of All-Electric Upgrades Requested,Percentage of All-Electric Upgrades completed
1,36,Jan,348,66,899,138,601,143,6,15,607,158,1247,204,72.093023,67.647059,99.011532,90.506329
2,37,Feb,363,103,956,186,611,232,11,15,622,247,1319,289,72.479151,64.359862,98.231511,93.927126
3,38,Mar,430,74,1215,110,950,135,8,13,958,148,1645,184,73.860182,59.782609,99.164927,91.216216
4,39,Apr,450,201,1412,300,778,417,11,35,789,452,1862,501,75.832438,59.88024,98.60583,92.256637
5,40,May,298,155,934,252,644,463,14,44,658,507,1232,407,75.811688,61.916462,97.87234,91.321499
6,41,Jun,320,130,914,234,352,380,8,24,360,404,1234,364,74.068071,64.285714,97.777778,94.059406
7,42,Jul,274,120,829,199,87,290,1,17,88,307,1103,319,75.158658,62.382445,98.863636,94.462541
8,43,Aug,265,152,830,266,81,386,2,36,83,422,1095,418,75.799087,63.636364,97.590361,91.469194
9,44,Sep,239,126,757,234,70,383,1,20,71,403,996,360,76.004016,65,98.591549,95.037221
10,45,Oct,259,138,804,295,80,447,1,33,81,480,1063,433,75.634995,68.12933,98.765432,93.125
11,46,Nov,243,103,681,248,55,318,1,23,56,341,924,351,73.701299,70.655271,98.214286,93.255132
12,47,Dec,193,107,632,218,51,323,2,19,53,342,825,325,76.606061,67.076923,96.226415,94.444444
13,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49,Total,3682,1475,10863,2680,4360,3917,66,294,4426,4211,14545,4155,74.685459,64.500602,98.508812,93.018285